### PR TITLE
added compatibility to simulate impinj xArray R680

### PR DESCRIPTION
**Pull request by HanYangZhao**
I used Wireshark to trace the LLRP protocol while testing with a Impinj xArray R680. From that and the llrp documentation, I was able to find the new message types needed in order to simulate the antenna using the golemu library

### CODE REVIEW

**Comment by iomz** [comment]
This will remove AirProtocolTagData from the TagReportData.
I need to redesign the constructors for the Parameters/Messages to take SetReaderConfig or ROSpec for what to be included in the TagReportData.

**Comment by kaysersoze** [comment]
Was AirProtocolTagData removed because the Impinj xArray R680 doesn't support that particular feature in the TagReportData?

I'm trying to get more acquainted with the underlying go-llrp library, since I'm interested in using golemu to emulate the Zebra FX series (FX9500/9600) of RFID readers, and they have similar support to the Impinj readers.

Thanks @iomz for some great software. It has been very helpful for my internal testing.

**Comment by iomz** [comment]
I'm pretty sure xArray R680 is fully conformal to the LLRP standard; not only AirProtocolTagData but also the ones in PR from @HanYangZhao (ChannelIndex, LastSeenTimestampUTC, and TagSeenCount). In addition, Impinj's readers have some vendor extensions.

There are two problems at the moment – 1.) no mechanisms implemented in go-llrp to construct TagReportData from given SetReaderConfig or ROSpec, and 2.) only limited parameters are implemented for TagReportData.

Meanwhile, I'm trying to refactor all the parameters and messages in go-llrp, by directly parsing the LLRP definition schema available from LTK: https://sourceforge.net/projects/llrp-toolkit/files/llrp-toolkit/ltkdef/1.0.0.8/ . That will be the next major update...

**Comment by iomz** [comment]
Merged this PR with the tentative fix 270654d3ca8613adb6d1ec7ca5c62cd83c7b4232. Thank you @HanYangZhao for adding the parameters!

**Pull request merged**
